### ISSUE TITLE
Bug - Can't submit review if I have no metrics defined

### ISSUE THREAD

**Issue by papeixoto** [RicardoPBarbosa/interview-tests-reviewer#1]
If I have no metrics created I can't submit a review
As you can see even though I have all fields filled the button is still disabled

<img width="958" alt="image" src="https://user-images.githubusercontent.com/14823708/236184395-d156c3e7-7e61-47c4-8799-3e2f863eac13.png">

**Comment by kamolmachine** [comment]
@RicardoPBarbosa Hey! I'd like to fix this bug. Could you explain what behavior is expected - should there be a warning message displayed that metrics need to be added before a review can be submitted, or should the button not be disabled if there are no metrics

**Comment by RicardoPBarbosa** [comment]
@comeall09
> @RicardoPBarbosa Hey! I'd like to fix this bug. Could you explain what behavior is expected - should there be a warning message displayed that metrics need to be added before a review can be submitted, or should the button not be disabled if there are no metrics

Thank you for taking an interest in fixing the bug!
What do you feel should happen? 😉
I'll accept the better-implemented solution!

**Notes**
* If you don't allow submissions without metrics, make sure you put a link to the metric creation page in there
* If you allow submissions without metrics, make sure the UI looks fine both on that page and on the "print view"/exported version (doesn't make sense to have the bottom padding on the final score background if there won't be an "average" label 😉)

**Comment by papeixoto** [comment]
Just [opened a PR](https://github.com/RicardoPBarbosa/interview-tests-reviewer/pull/3).

I went with the second approach of allowing users to submit a review without metrics because that seems like a fair use case.
Since right now, if we have 2 metrics created, we just need to have one of them scored I just removed that restriction from the disable of the submit button.
